function PXI=CARDAMOM_PROJECT_SUBSET_PXI(PXIfull,subset,pname)

%PXIfull: generated by CARDAMOM_PROJECT
%subset: can be a vector of indices in PXI, or a map corresponding to
%PXI.MASK
%pname: the new project name (default = blank)


if nargin<3;pname='';end
%Step 1. subset all fields
PXI=PXIfull;


%Maps
if isvector(subset)
ptsall=find(PXI.MASK);
ptsmask=ptsall(subset);
else
    %Map of 1s and 0s
    %Ensure Mask only includes PXI mask
    subset=subset.*PXI.MASK;
    %Find subset of points corresponding to mask
    ptsall=find(PXI.MASK);
    ptsmask=find(subset==1);
    [~,ptsss]=ismember(ptsmask,ptsall); 
    
end
    

%Project name

%******maps*******
%MASK
PXI.MASK(ptsall)=false;
PXI.MASK(ptsmask)=true;
%Project name
PXI.run_name=[PXI.run_name,pname];
%ID map
PXI.pixelidmap(PXI.MASK==0)=0;
%PXI.pixelnmap=PXI.pixelnmap*0;
%PXI.pixelnmap(ptsss)=1:numel(ptsss);

% %
%    lon: [1x63590 double]
%             lat: [1x63590 double]
%               r: [1x63590 double]
%               c: [1x63590 double]
%         pixelid: {1x63590 cell}
%     cbffilename: {63590x1 cell}

PXI.lon=PXI.lon(ptsss);
PXI.lat=PXI.lat(ptsss);
PXI.r=PXI.r(ptsss);
PXI.c=PXI.c(ptsss);
PXI.pixelid=PXI.pixelid(ptsss);
PXI.cbffilename=PXI.cbffilename(ptsss);





end