cbffile='/Users/abloom/CARDAMOM_DISK/CBF_FILES/GCRUN_JUN20_TDLE/GCRUN_JUN20_TDLE_1942.cbf';
cbrfile='/Users/abloom/CARDAMOM_DISK/PROJECTS/GCRUN_JUN20_TDLE/cbr_files/GCRUN_JUN20_TDLE_1942_1.cbr';

CBR=CARDAMOM_RUN_MODEL(cbffile,cbrfile);